<a href="https://colab.research.google.com/github/Girawale-Sanket/Time-Series-Assignment/blob/main/Time_SA_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.stats.diagnostic import acorr_ljungbox
from statsmodels.stats.stattools import durbin_watson

In [ ]:
data=pd.read_excel('/content/Non-Tax Revenue data.xlsx')

In [ ]:
data.describe()

                      Date          Value
count                  288     253.000000
mean   2009-12-15 23:00:00   11164.849802
min    1998-01-01 00:00:00   -2842.000000
25%    2003-12-24 06:00:00    3902.000000
50%    2009-12-16 12:00:00    7142.000000
75%    2015-12-08 18:00:00   11745.000000
max    2021-12-01 00:00:00  154716.000000
std                    NaN   16091.942415

In [ ]:
from datetime import datetime
data['Date'] = pd.to_datetime(data['Date'], format='%d-%m-%Y')
data['Date'].dtype

dtype('<M8[ns]')

In [ ]:
data.isnull().sum()

Date      0
Value    35
dtype: int64