In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [15]:
data=pd.read_csv('/content/sample_data/Bhubaneshwer_data.csv')

In [16]:
data.head()

  Calendar Day  Sales Qty 5Y
0   11-10-2017           0.5
1   12-10-2017           0.5
2   23-11-2017           0.5
3   24-11-2017           0.5
4   06-12-2017           1.0

In [17]:
data.shape

(706, 2)

In [18]:
data.isnull().sum()

Calendar Day    0
Sales Qty 5Y    0
dtype: int64

In [19]:
data.describe()

       Sales Qty 5Y
count    706.000000
mean       9.314589
std        9.371686
min        0.050000
25%        2.668750
50%        6.500000
75%       12.500000
max       59.600000

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 706 entries, 0 to 705
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Calendar Day  706 non-null    object
 1   Sales Qty 5Y  706 non-null    float64
dtypes: float64(1), object(1)
memory usage: 11.2+ KB

In [21]:
data['Calendar Day'] = pd.to_datetime(data['Calendar Day'], format='%d-%m-%Y')

In [22]:
data['Calendar Day'].dtype

dtype('<M8[ns]')

In [23]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 706 entries, 0 to 705
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Calendar Day  706 non-null    datetime64[ns]
 1   Sales Qty 5Y  706 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 11.2 KB

In [24]:
#sorting
data = data.sort_values("Calendar Day").reset_index(drop=True)
data.set_index("Calendar Day", inplace=True)

In [25]:
data.head()

              Sales Qty 5Y
Calendar Day
2017-10-11             0.5
2017-10-12             0.5
2017-11-23             0.5
2017-11-24             0.5
2017-12-06             1.0